# Generated by Django 3.2.15 on 2022-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarm_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('src', models.CharField(blank=True, max_length=100, null=True)),
                ('turn', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'alarm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('images_id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(blank=True, max_length=100, null=True)),
                ('yolo_category', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LostItems',
            fields=[
                ('lost_items_id_pk', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('get_name', models.CharField(blank=True, max_length=150, null=True)),
                ('get_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('get_place', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('find_place', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_check', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lost_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='upload_image/')),
                ('category', models.CharField(max_length=15)),
                ('uploaded_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploaded_image',
                'managed': False,
            },
        ),
    ]
