# Generated by Django 3.2.15 on 2022-09-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
