# Generated by Django 4.1.1 on 2022-09-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fast_search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("imageNmae", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="upload_image/"),
        ),
    ]
