# Generated by Django 3.2.15 on 2022-09-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acha_money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsDeal',
            fields=[
                ('posts_id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_check', models.CharField(blank=True, max_length=10, null=True)),
                ('find_check', models.CharField(blank=True, max_length=10, null=True)),
                ('send_check', models.CharField(blank=True, max_length=10, null=True)),
                ('accept_check', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'posts_deal',
                'managed': False,
            },
        ),
    ]
