# Generated by Django 3.2.15 on 2022-09-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acha_money', '0002_userdeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
